<?php
$this->headTitle('Карточка документа');

$this->mainMenu()->setActiveItemId('documents');

$this->pageBreadcrumbs()->setItems([
            'Дом'=>$this->url('home'),
            'Менеджер документов'=>$this->url('documents'),
            'Карточка документа'=>$this->url('documents', ['action'=>'view', 'id'=>$documents->getId()])
            ]);
?>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<h1>Карточка документа</h1>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
             <tr>
                <th>ID:</th>
                <td><?= $this->escapeHtml($documents->getId()) ?></th>
            </tr>
            <tr>
                <th>имя документа:</th>
                <td><?= $this->escapeHtml($documents->getName()) ?></th>
            </tr>
            <tr>
                <th>номер документа:</th>
                <td><?= $this->escapeHtml($documents->getNumber()) ?></th>
            </tr>
            <tr>
                <th>Кем выдан:</th>
                <td><?= $this->escapeHtml($documents->getDepartIssue()) ?></th>
            </tr>
            <tr>
                <th>Дата выдачи:</th>
                <td><?= $this->escapeHtml($documents->getDateIssue()) ?></th>
            </tr>
            <tr>
                <th>Автор:</th>
                <td><?= $this->escapeHtml($documents->getAuthor()) ?></th>
            </tr>
        </table>
    </div>
</div>